# .github/workflows/build-and-push.yml
name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  # Define your Docker image name (replace with your Docker Hub username/repo)
  IMAGE_NAME: anuragox/portfolio-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Ensure only pushes to main (or releases) trigger the push
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Requires DOCKERHUB_TOKEN secret in GitHub

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          # Tag with 'latest' and Git SHA
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=sha,prefix=,format=long

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true # Enable pushing
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # Use the builder stage from your Dockerfile for efficiency
          target: runner # Target the final stage that contains the production-ready app
          # Pass build arguments if needed (e.g., NEXT_PUBLIC_* vars)
          # build-args: |
          #   NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}
