name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm" # Use 'yarn' or 'pnpm' if applicable

      - name: Install dependencies
        run: npm ci # Use 'yarn install --frozen-lockfile' or 'pnpm install --frozen-lockfile' if applicable

      - name: Run Linter
        run: npm run lint # Ensure this script exists in package.json

      - name: Build Application
        run: npm run build
    # - name: Run Unit Tests
    #   run: npm run test
    # Add your unit test command here if you have them
    # Example: npm run test
